"""SmithHunter2: small RNA discovery across user-selected genomes (module A, rule `all`)
and target prediction (module B, rule `targets`)."""

configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/preprocess.smk"
include: "rules/mapping.smk"
include: "rules/discovery.smk"
include: "rules/targets.smk"


rule all:
    input:
        OUT / "discovery/loci.tsv",
        OUT / "discovery/candidates.fasta",
        OUT / "origin/origin_summary.tsv",
        OUT / "origin/length_distribution.tsv",
        expand(OUT / "qc/{sample}.fastp.json", sample=SAMPLES),
